version: "3.8"
services:
  # app:
  #   container_name: "sipartan-be"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - SECRETKEY=12345
  #     - DB_HOST=db
  #     - DB_USER=postgres
  #     - DB_PASS=postgres
  #     - DB_NAME=sipartan-db-local
  #     - DB_PORT=5432
  #   ports:
  #     - "9001:8081"
  #   networks:
  #     - default
  #   depends_on:
  #     - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sipartan-db-local
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:

volumes:
  pgdata:
